### ISSUE TITLE
Enhance GAE backend with partial requests.

### ISSUE THREAD

**Issue by jamie255** [dima/restfulx#14]
Google App Engine is very sensitive to retrievals that take a long time or use too much CPU. In my existing application I'm getting log messages like this: /payments.xml 200 1624ms 3670cpu_ms 2368api_cpu_ms 193kb  with a tooltip message that says "This request used a high amount of CPU and may soon exceed its quota."

My request-for-enhancement, then, is a way to request partial amounts of data.

**Comment by dima** [comment]
You can do anything a typical Rails app would do to limit the amount of data retrieved. E.g. paging, etc. The generated GAE code is just a starting point.
