### ISSUE TITLE
uninitialized constant RestfulX::ActiveRecord::Serialization

### ISSUE THREAD

**Issue by ximus** [dima/restfulx#17]
Had a problem loading 1.3.0:

`load_missing_constant': uninitialized constant RestfulX::ActiveRecord::Serialization (NameError)
(...)
from /Users/johnwest/.bundle/ruby/1.8/bundler/gems/restfulx-4c800dcb763416a71965ab45e5fadba4eb9ef01d-master/rails/../lib/restfulx/active_record.rb:6
(...)

The following change did the trick:

lib/restfulx/active_record.rb:6
- \- - class AMFSerializer < ActiveRecord::Serialization::Serializer
  +++class AMFSerializer < ::ActiveRecord::Serialization::Serializer

Running Rails 2.3.5
gems loaded via Bundler
OSX
ruby 1.8.7 (system)

(copy paste from my comment on the google group)

**Comment by dima** [comment]
Thanks a lot for jumping in and trying this out. Will have a look at the issue ASAP.

**Comment by dima** [comment]
Fixed
