### ISSUE TITLE
 rake db:schema:to_yaml with Rails 2.3  - nil object

### ISSUE THREAD

**Issue by shanlalit** [dima/restfulx#2]
On a Rails 2.3 project 
 rake db:schema:to_yaml
breaks with
  You have a nil object when you didn't expect it!
  The error occurred while evaluating nil.gsub

I fixed it by replacing

schema_to_yaml.rb line number 98

  last_in_array_fix = last_in_array_fix.gsub(', ','')

with

  last_in_array_fix = last_in_array_fix.gsub(', ','') unless last_in_array_fix.nil?

**Comment by ahabman** [comment]
Worked for me.  Thanks!  I did  have to search for the file, mine as at /usr/lib/ruby/gems/1.8/gems/restfulx-1.2.4/lib/restfulx/rails/schema_to_yaml.rb

**Comment by dima** [comment]
Closed by 2bfb3742eff7badac4aef8b660b1fd9082c80131
