### ISSUE TITLE
rails g rx_config error

### ISSUE THREAD

**Issue by zbage** [dima/restfulx#25]
Bundler could not find compatible versions for gem "activesupport": (Bundler::VersionConflict)
  In Gemfile:
    restfulx depends on
      activesupport (~> 2.3.5)

```
rails (= 3.0.3) depends on
  activesupport (3.0.3)
```

**Comment by dima** [comment]
Rails 3 not currently supported. Flex4/Rails 3 compatibility rewrite/update is planned for 1.4.0 (next release).
