### ISSUE TITLE
RxAutoComplete could have an option to always hit the server

### ISSUE THREAD

**Issue by elvisfernandes** [dima/restfulx#5]
It would be useful if RxAutoComplete had a flag to indicate if it should search the typed word in cache before trying to hit the server or always ask the server, without to consider the cached objects.

**Comment by dima** [comment]
This is a client-side (not server-side) issue (and should be raised against restfulx_framework)

**Comment by elvisfernandes** [comment]
Oh, I'm sorry. Perhaps I was distracted. And I created a ticket for this 2 months ago on the right project (http://github.com/dima/restfulx_framework/issues/#issue/22).

I'm really sorry! :-)
